
name: Run Experiment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run experiment that reports to Weights & Biases
      run: python train.py
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    - name: Report WandB Results
      uses: bencevans/wandb-action@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

        # Optional. Defaults to the repository owner/name.
        # WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
        # WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}